version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    # Add if you need to wait for database
    # depends_on:
    #   - db

  frontend:
    build: ./frontend
    container_name: frontend_service
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent node_modules from being overwritten
      - /app/.next         # Prevent .next from being overwritten
    working_dir: /app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

