services:
  backend:
    build: ./backend
    container_name: backend_service
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - internal-network
  frontend:
    build: ./frontend
    container_name: frontend_service
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - internal-network
  
  networks:
  internal-network:
    driver: bridge

